(() => {
  const ns = window.HtmlSlideMenderExtension = window.HtmlSlideMenderExtension || {};
  const MESSAGE_NAMESPACE = "HTML_SLIDE_MENDER";
  const EDITOR_BUILD_ID = "2026-06-13-html-slide-mender";
  const ROOT_ID = "html-slide-mender-root";
  const TEXT_SELECTOR = [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "span",
    "li",
    "blockquote",
    "button",
    "a",
    "label",
    "figcaption",
    "caption",
    "td",
    "th",
    "div",
    "[data-editable]"
  ].join(",");
  const BLOCK_TEXT_SELECTOR = "h1,h2,h3,h4,h5,h6,p,li,blockquote,button,label,figcaption,caption,td,th";
  const EXCLUDED_SELECTOR = [
    "script",
    "style",
    "noscript",
    "svg",
    "canvas",
    "iframe",
    "video",
    "audio",
    "template",
    `[id="${ROOT_ID}"]`
  ].join(",");

  const FONTS = [
    { label: "Default", value: "" },
    { label: "Arial", value: "Arial, sans-serif" },
    { label: "Helvetica", value: "Helvetica, Arial, sans-serif" },
    { label: "Inter", value: "Inter, Arial, sans-serif" },
    { label: "Noto Sans SC", value: "\"Noto Sans SC\", sans-serif" },
    { label: "Noto Serif SC", value: "\"Noto Serif SC\", serif" },
    { label: "Source Han Sans", value: "\"Source Han Sans SC\", \"Noto Sans SC\", sans-serif" },
    { label: "Source Han Serif", value: "\"Source Han Serif SC\", \"Noto Serif SC\", serif" },
    { label: "PingFang SC", value: "\"PingFang SC\", sans-serif" },
    { label: "Microsoft YaHei", value: "\"Microsoft YaHei\", sans-serif" }
  ];

  const FONT_SIZES = [
    6, 8, 10, 11, 12, 14, 16, 18,
    20, 22, 24, 26, 28, 30, 32, 34,
    36, 38, 40, 44, 48, 56, 64, 72,
    84, 100
  ];

  const OFFICE_COLORS = [
    "#000000", "#404040", "#808080", "#BFBFBF", "#FFFFFF",
    "#C00000", "#FF0000", "#FFC000", "#FFFF00", "#92D050",
    "#00B050", "#00B0F0", "#0070C0", "#002060", "#7030A0",
    "#F4CCCC", "#FCE5CD", "#FFF2CC", "#D9EAD3", "#D0E0E3",
    "#CFE2F3", "#D9D2E9", "#EADCF8", "#EA9999", "#F9CB9C",
    "#FFE599", "#B6D7A8", "#A2C4C9", "#9FC5E8", "#B4A7D6",
    "#CC0000", "#E69138", "#F1C232", "#6AA84F", "#45818E",
    "#3D85C6", "#674EA7", "#990000", "#B45F06", "#BF9000",
    "#38761D", "#134F5C", "#0B5394", "#351C75"
  ];

  const LANG_STORAGE_KEY = "htmlSlideMenderLanguage";
  const COLOR_HISTORY_STORAGE_KEY = "htmlSlideMenderColorHistory";
  const EXPORT_MODE_STORAGE_KEY = "htmlSlideMenderExportMode";
  const DEFAULT_LANG = "zh-CN";
  const I18N = {
    "zh-CN": {
      ready: "正在识别当前页面...",
      collapseTitle: "收起编辑器",
      appName: "HTML Mender",
      undo: "撤销",
      redo: "重做",
      addText: "新增文字",
      addImage: "新增图片",
      rescan: "重新识别",
      boxes: "编辑框",
      boxesOn: "编辑框 开",
      boxesOff: "编辑框 关",
      contentMode: "文字/图片",
      layoutMode: "位置微调",
      saveMode: "保存",
      saveDraft: "保存草稿",
      basicHtml: "基础 HTML",
      fullHtml: "完整 HTML",
      download: "下载 HTML",
      exit: "退出",
      size: "字号",
      sizeDown: "减小字号",
      sizeUp: "增大字号",
      textColor: "文字",
      highlight: "高亮",
      recentColors: "最近使用",
      presetColors: "标准颜色",
      moreColors: "更多颜色",
      noRecentColors: "暂无历史颜色",
      left: "左对齐",
      center: "居中",
      right: "右对齐",
      line: "行高",
      replace: "替换图片",
      cover: "填满",
      contain: "适应",
      fill: "拉伸",
      zoomOut: "缩小",
      zoomIn: "放大",
      reset: "重置",
      language: "English",
      textLabel: "文字",
      imageLabel: "图片",
      layoutLabel: "位置",
      positioned: "定位元素",
      overflow: "溢出",
      changed: "处修改",
      textUnit: "文字",
      imageUnit: "图片",
      layoutUnit: "版面",
      resetLayout: "恢复",
      moveScaleMode: "移动缩放",
      sizeMode: "改宽高",
      layoutAlignLeft: "左齐",
      layoutAlignHCenter: "水平居中",
      layoutAlignRight: "右齐",
      layoutAlignTop: "上齐",
      layoutAlignVCenter: "垂直居中",
      layoutAlignBottom: "下齐",
      layoutSameWidth: "同宽",
      layoutSameHeight: "同高",
      layoutSameSize: "同宽高",
      scaleLayout: "缩放",
      resizeLayout: "改宽高",
      started: "编辑器已启动。",
      alreadyActive: "编辑器已在运行。",
      exited: "已退出编辑模式。",
      boxesVisible: "编辑框已显示。",
      boxesHidden: "编辑框已隐藏。",
      rescanned: "已重新识别当前页面。",
      editingCurrentView: "正在编辑当前画面。蓝框是文字，绿框是图片。",
      nothingUndo: "没有可撤销的操作。",
      nothingRedo: "没有可重做的操作。",
      undone: "已撤销。",
      redone: "已重做。",
      newTextPlaceholder: "双击编辑文字",
      textAdded: "已新增文字。",
      imageAdded: "已新增图片。",
      unsupportedImage: "暂不支持这种图片格式。",
      imageReplaced: "图片已替换。",
      imageReset: "图片已重置。",
      layoutModeOn: "已进入版面微调模式。",
      layoutModeOff: "已退出版面微调模式。",
      layoutReset: "版面已恢复。",
      htmlReady: "HTML 已准备好。",
      downloadStarted: "HTML 下载已开始。",
      draftSaved: "草稿已保存，刷新后会自动恢复。",
      draftSaveFailed: "草稿保存失败，请下载 HTML 保存。",
      notActive: "编辑器未启动。",
      languageSet: "语言已切换。"
    },
    en: {
      ready: "Scanning current view...",
      collapseTitle: "Collapse editor",
      appName: "HTML Mender",
      undo: "Undo",
      redo: "Redo",
      addText: "Add text",
      addImage: "Add image",
      rescan: "Rescan",
      boxes: "Boxes",
      boxesOn: "Boxes on",
      boxesOff: "Boxes off",
      contentMode: "Text/Image",
      layoutMode: "Move layout",
      saveMode: "Save",
      saveDraft: "Save draft",
      basicHtml: "Basic HTML",
      fullHtml: "Full HTML",
      download: "Download HTML",
      exit: "Exit",
      size: "Size",
      sizeDown: "Smaller",
      sizeUp: "Larger",
      textColor: "Text",
      highlight: "Mark",
      recentColors: "Recent",
      presetColors: "Standard",
      moreColors: "More colors",
      noRecentColors: "No recent colors",
      left: "Left",
      center: "Center",
      right: "Right",
      line: "Line",
      replace: "Replace",
      cover: "Cover",
      contain: "Contain",
      fill: "Fill",
      zoomOut: "Zoom -",
      zoomIn: "Zoom +",
      reset: "Reset",
      language: "中文",
      textLabel: "Text",
      imageLabel: "Image",
      layoutLabel: "Move",
      positioned: "positioned",
      overflow: "overflow",
      changed: "changed",
      textUnit: "text",
      imageUnit: "images",
      layoutUnit: "layout",
      resetLayout: "Reset",
      moveScaleMode: "Move/scale",
      sizeMode: "Resize",
      layoutAlignLeft: "Left",
      layoutAlignHCenter: "H center",
      layoutAlignRight: "Right",
      layoutAlignTop: "Top",
      layoutAlignVCenter: "V center",
      layoutAlignBottom: "Bottom",
      layoutSameWidth: "Same W",
      layoutSameHeight: "Same H",
      layoutSameSize: "Same size",
      scaleLayout: "Scale",
      resizeLayout: "Resize",
      started: "Editor started.",
      alreadyActive: "Editor already active.",
      exited: "Editor exited.",
      boxesVisible: "Edit boxes visible.",
      boxesHidden: "Edit boxes hidden.",
      rescanned: "Current view rescanned.",
      editingCurrentView: "Editing current view. Text is blue, images are green.",
      nothingUndo: "Nothing to undo.",
      nothingRedo: "Nothing to redo.",
      undone: "Undone.",
      redone: "Redone.",
      newTextPlaceholder: "Double-click to edit text",
      textAdded: "Text added.",
      imageAdded: "Image added.",
      unsupportedImage: "Unsupported image type.",
      imageReplaced: "Image replaced.",
      imageReset: "Image reset.",
      layoutModeOn: "Layout adjustment mode on.",
      layoutModeOff: "Layout adjustment mode off.",
      layoutReset: "Layout reset.",
      htmlReady: "HTML ready.",
      downloadStarted: "HTML download started.",
      draftSaved: "Draft saved. It will restore after refresh.",
      draftSaveFailed: "Draft save failed. Download HTML instead.",
      notActive: "Editor is not active.",
      languageSet: "Language switched."
    }
  };

  ns.constants = {
    MESSAGE_NAMESPACE,
    EDITOR_BUILD_ID,
    ROOT_ID,
    TEXT_SELECTOR,
    BLOCK_TEXT_SELECTOR,
    EXCLUDED_SELECTOR,
    FONTS,
    FONT_SIZES,
    OFFICE_COLORS,
    LANG_STORAGE_KEY,
    COLOR_HISTORY_STORAGE_KEY,
    EXPORT_MODE_STORAGE_KEY,
    DEFAULT_LANG,
    I18N
  };
})();
